#version: "4"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123  
      MYSQL_DATABASE: gestion_tasks
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
    ports:
      - "8080:80"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    container_name: backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root123
      DB_NAME: gestion_tasks
    networks:
      - app-network
    depends_on:
      - mysql

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    environment:
      REACT_APP_BACKEND_URL: http://backend:3001/api
    networks:
      - app-network
    depends_on:
      - backend

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
